CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS goals (
 id BIGSERIAL PRIMARY KEY,
 title VARCHAR(255) NOT NULL,
 description TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS projects (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 description TEXT,
 status VARCHAR(40) NOT NULL DEFAULT 'PLANNED',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
 id BIGSERIAL PRIMARY KEY,
 title VARCHAR(255) NOT NULL,
 description TEXT,
 status VARCHAR(40) NOT NULL DEFAULT 'TODO',
 assigned_agent VARCHAR(100),
 project_id BIGINT REFERENCES projects(id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS documents (
 id BIGSERIAL PRIMARY KEY,
 title VARCHAR(255) NOT NULL,
 content TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS knowledge_chunks (
 id BIGSERIAL PRIMARY KEY,
 document_id BIGINT REFERENCES documents(id) ON DELETE CASCADE,
 content TEXT NOT NULL,
 embedding vector(1536),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS agent_runs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 agent_code VARCHAR(100) NOT NULL,
 input JSONB NOT NULL,
 output JSONB,
 status VARCHAR(40) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
